Update curl.d
* Fixed missing http variable
* Fixed deprecated concatenation 
```
Error: Implicit string concatenation is deprecated, use "http://upload.wikimedia.org/wikipedia/commons/" ~ "5/53/Wikipedia-logo-en-big.png" instead
```