# This is a combination of 3 commits. # The first commit's message is: # This is a combination of 10 commits. # The first commit's message is: # This is a combination of 2 commits. # The first commit's message is:
# This is a combination of 5 commits.
# The first commit's message is:
Tuple's toString made useful.

http://forum.dlang.org/thread/srofuqyrdzphgzylbwds@forum.dlang.org
Format Tuple's fields with format in %(%|%), similar to arrays, or, without %|, each filed specifically.

Doesn't break any existing code as %s qualifier's behavior is not modified

The overload without parameters is intentionally left as a template, as it appears
to reveal some bugs in std.format for certain types. Remove the
template parameter list to reproduce.

# This is the 2nd commit message:

dynamically load libcurl

- avoids issues with versioned symbols on different platforms
- lazy loading/initialization of curl library
- fix Issue 13324
- try to load curl from the exe itself before loading a shared library
  thus allowing to link against a different or a static curl library

# This is the 3rd commit message:

fix Issue 14949 - Non-descriptive "Enforcement failed" when attempting to write to closed file

# This is the 4th commit message:

remove data argument from options

- it's unlikely that the non-usage of
  OPTIONS body changes anytime soon

# This is the 5th commit message:

Allow Variant.visit to support const types.

Assuming that Foo.depth and Bar.depth are both const (e.g. both are just int
members), the following should compile:
-----
    int depth(in FooBar fb) {
        return fb.visit!((Foo foo) => foo.depth,
                         (Bar bar) => bar.depth);
    }
-----

However, it was failing with:
std/variant.d(2246): Error: cannot implicitly convert expression (variant.peek())
of type const(Foo)* to Foo*
std/variant.d(2246): Error: cannot implicitly convert expression (variant.peek())
of type const(Bar)* to Bar*

This patch changes an explicit `T*` declaration to an `auto` declaration so
const types can be visited.

# This is the 2nd commit message:

fix docs for HTTP only requests

# This is the 2nd commit message:

Fix broken hyperlinks to std.algorithm submodules.

# This is the 3rd commit message:

Leading rows in Container Primitives table should span all columns.

Depends on: https://github.com/D-Programming-Language/dlang.org/pull/1071

# This is the 4th commit message:

Add missing references to std.digest.hmac to fix doc generation

# This is the 5th commit message:

Added Andrei's Getting Started Guide
# This is the 6th commit message:

Fix Issue 14884

# This is the 7th commit message:

Ignore .lst files
# This is the 8th commit message:

Add sameHead/sameTail to function list in docs.

# This is the 9th commit message:

std.traits.hasMember: just forward to __traits(hasMember, ...)

This way opDispatch'ed members are recognized.

Fixes issue 14605 - RefAppender fails isOutputRange.

# This is the 10th commit message:

Ddoc: add missing parenthesis

# This is the 2nd commit message:

Added ///

# This is the 3rd commit message:

Added attributes; clearify Documentation