std.exception: Make unittest less brittle
It makes sure the source file can be read from when running the tests.
If the path to std/exception.d in the compile-Phobos command line was
relative, this required the testrunner to be run in the same working
directory as when compiling Phobos.