Bugfix for "undefined identifier _min" in SharedFreeList.
When instantiating SharedFreeList with a 0 minSize and a
chooseAtRuntime maxSize, it will give an error like so:

  std/experimental/allocator/building_blocks/free_list.d(822): Error: undefined identifier _min, did you mean alias min?

This commit resolves the error message by using 'min' instead
of '_min', because '_min' is only available when
(minSize == chooseAtRuntime).