Make conv unittest private simbols private
There were some symbols in a "version(unittest)" block that were not declared private.

This can create some conflicts during unittest releases. I started out just declaring them private, but that created some ambiguities in other modules that used "A" in their names, eg:
```D
struct Appender(A : T[], T)
```

`std\array.d(2129): Error: module std.array std.conv.A is private`.

So I just mangled the names. As a workaround. I'll file a bug report later.